# FROM quay.io/fedora-ostree-desktops/kinoite:41
FROM quay.io/fedora-ostree-desktops/base:41

# Install KDE Plasma
# RUN dnf install -y @kde-desktop-environment && systemctl enable sddm

# Install COSMIC
# RUN dnf install -y @cosmic-desktop-environment && dnf install -y @container-management && dnf install -y flatpak sddm && \
#     systemctl disable -f cosmic-greeter greetd && \
#     systemctl enable -f sddm && \
#     dnf copr enable -y ryanabx/cosmic-epoch && dnf install -y cosmic-desktop && \
#     dnf upgrade --refresh -y && \
#     dnf clean all

RUN dnf install -y @container-management
RUN dnf copr enable -y ryanabx/cosmic-epoch
RUN dnf install -y cosmic-desktop \
    tuned tuned-ppd
RUN dnf copr enable -y lukenukem/asus-linux && dnf install -y supergfxctl && systemctl enable supergfxd.service
# RUN dnf copr enable -y mrduarte/LenovoLegionLinux && dnf install -y dkms-LenovoLegionLinux python-LenovoLegionLinux
RUN dnf upgrade --refresh -y
RUN dnf clean all
RUN systemctl enable cosmic-greeter tuned tuned-ppd
# RUN systemctl disable --force cosmic-greeter greetd && systemctl enable --force sddm

# Not used (not working)
# RUN dnf install -y kernel-headers kernel-devel dmidecode lm_sensors python3-PyQt6 python3-yaml python3-pip python3-argcomplete python3-darkdetect
# RUN dnf groupinstall -y "Development Tools"
# RUN dnf group install -y "C Development Tools and Libraries"
# Install the following for installation with DKMS
# RUN dnf install -y dkms openssl mokutil
# RUN git clone https://github.com/johnfanv2/LenovoLegionLinux.git && cd LenovoLegionLinux/kernel_module && make && make reloadmodule && cd ../.. && rm -rf LenovoLegionLinux

# Import vscode repo
# RUN rpm --import https://packages.microsoft.com/keys/microsoft.asc && \
# echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" | sudo tee /etc/yum.repos.d/vscode.repo > /dev/null

# # Install stuff (applications to start)
# RUN dnf remove -y power-profiles-daemon && \
#     dnf install -y \
#     # Virtualbox-7.0 \
#     # Git lfs
#     git git-lfs \
#     # Rust
#     rust cargo rust-analyzer rustfmt clippy \
#     # Other dev dependencies
#     wayland-devel libxkbcommon-devel fuse-devel squashfs-tools gstreamer1-plugins-base-devel gdk-pixbuf2-devel pango-devel gtk3-devel glib2-devel lld make automake gcc gcc-c++ clang clang-devel mold kernel-devel glibc-devel binutils binutils-devel binutils-gold \
#     # Git forge CLIs
#     gh pagure-cli \
#     # Fedora packaging stuff
#     fedpkg fedora-packager \
#     # Phone dev tools
#     android-tools pmbootstrap \
#     # Requirement for bootc image builder
#     osbuild-selinux \
#     # Ruby
#     ruby ruby-devel \
#     # Node.js
#     nodejs \
#     # cosmic-comp devel
#     libseat-devel pixman-devel \
#     # KDE devel
#     cmake \
#     # OS Specific stuff
#     # Code editors
#     code \
#     # Qemu and virt-manager
#     qemu virt-manager \
#     # Tuned!
#     tuned tuned-ppd && \
#     # Cosmic-epoch
#     dnf copr enable -y ryanabx/cosmic-epoch && dnf install -y cosmic-desktop && \
#     dnf clean all
