FROM fedora:latest

# Install rust and deps
RUN sudo dnf install -y rustc cargo rust-analyzer rustfmt clippy

# Install some other deps that I use in my projects
RUN sudo dnf install -y wayland-devel libxkbcommon-devel

# Install visual studio code in the container
RUN rpm --import https://packages.microsoft.com/keys/microsoft.asc && \
    echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" | sudo tee /etc/yum.repos.d/vscode.repo > /dev/null && \
    dnf check-update && \
    dnf install -y code # or code-insiders

# Install gh cli
RUN dnf install -y gh

# Run vscode
CMD code