# see https://github.com/osbuild/bootc-image-builder?tab=readme-ov-file#anaconda-iso-installer-options-installer-mapping
# caveat, must select manual partitioning and label `/boot` with `boot`
[customizations.installer.kickstart]
contents = ""