FROM quay.io/fedora/fedora-kinoite:latest
# FROM quay.io/fedora-ostree-desktops/base

# Import vscode repo
RUN rpm --import https://packages.microsoft.com/keys/microsoft.asc && \
echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" | sudo tee /etc/yum.repos.d/vscode.repo > /dev/null

RUN wget https://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo -O /etc/yum.repos.d/virtualbox.repo

# Install stuff (applications to start)
RUN rpm-ostree install virtualbox code vim \
# for cosmic
    gnome-keyring power-profiles-daemon \
    # Git lfs
    git-lfs \
    # Rust stuff
    rust cargo rust-analyzer rustfmt clippy \
    # Dev dependencies
    wayland-devel libxkbcommon-devel fuse-devel \
    squashfs-tools gstreamer1-plugins-base-devel \
    gdk-pixbuf2-devel pango-devel gtk3-devel glib2-devel \
    lld make automake gcc gcc-c++ clang clang-devel mold kernel-devel glibc-devel binutils binutils-devel binutils-gold \
    # Git forge CLIs
    gh pagure-cli \
    # Fedora packaging stuff
    fedpkg fedora-packager \
    # Phone dev tools
    android-tools pmbootstrap \
    # Tuned, for power management
    # tuned tuned-ppd
    # Requirement for bootc image builder
    osbuild-selinux \
    # Qemu and virt-manager
    qemu virt-manager virt-viewer \
    # Ruby
    ruby ruby-devel \
    # Node.js
    nodejs \
    # cosmic-comp devel
    libseat-devel pixman-devel \
    # KDE devel
    cmake
# Symlink ld because alternatives are brocken </3 https://github.com/coreos/rpm-ostree/issues/1614
RUN ln -s /usr/bin/ld.bfd /usr/bin/ld

# Add cosmic packages for testing ryanabx-shell
RUN wget https://copr.fedorainfracloud.org/coprs/ryanabx/cosmic-epoch/repo/fedora-$(rpm -E %fedora)/ryanabx-cosmic-epoch-fedora-$(rpm -E %fedora).repo -O /etc/yum.repos.d/_copr_ryanabx-cosmic.repo
RUN rpm-ostree install cosmic-desktop

# ENV CARGO_HOME /workdir/.cargo
# RUN mkdir -p /workdir

# WORKDIR /workdir

# RUN git clone https://github.com/ryanabx/ryanabx-session && cd ryanabx-session && ./build-install-ryanabx-shell.sh && ./install-session.sh

# WORKDIR /

# RUN rm -rf /workdir
