# FROM ghcr.io/ublue-os/cosmic-base:40
FROM quay.io/fedora/fedora-kinoite:latest
# FROM quay.io/fedora-ostree-desktops/kinoite:40

RUN rpm --import https://packages.microsoft.com/keys/microsoft.asc && \
echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" | sudo tee /etc/yum.repos.d/vscode.repo > /dev/null && \
# Install stuff (applications to start)
    rpm-ostree install code qemu virt-manager \
# Rust development
    rust cargo rust-analyzer rustfmt clippy \
# Dev dependencies
    wayland-devel libxkbcommon-devel fuse-devel \
    squashfs-tools gstreamer1-plugins-base-devel \
    gdk-pixbuf2-devel pango-devel gtk3-devel glib2-devel \
    lld \
# Git forge CLIs
    gh pagure-cli \
# Fedora packaging stuff
    fedpkg fedora-packager \
# Phone dev tools
    android-tools pmbootstrap && \
# Finish
    ostree container commit && \
    mkdir -p /var/tmp && chmod -R 1777 /var/tmp