name: cosmic-bootc-iso

on:
  workflow_dispatch:

jobs:
  build-iso:
    name: Build ISO
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Maximize build space
        uses: ublue-os/remove-unwanted-software@v7
        with:
          remove-android: 'true'
      
      - name: Build iso
        run: |
          mkdir output && sudo apt update && sudo apt install -y podman && sudo podman run \
          --rm \
          -it \
          --privileged \
          --pull=newer \
          --security-opt label=type:unconfined_t \
          -v $(pwd)/extra/bootc-config.toml:/config.toml:ro \
          -v $(pwd)/output:/output \
          quay.io/centos-bootc/bootc-image-builder:latest \
          --type anaconda-iso \
          --rootfs btrfs \
          ghcr.io/ryanabx/cosmic-bootc

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: cosmic-bootc-iso
          path: output/bootiso/